package project.server.views.utility;

public enum ServerPanels {
    HOME_PANEL,
    VIEW_BOOKS_PANEL,
    MANAGE_BOOK_PANEL,
    MANAGE_ACCOUNTS_PANEL,
    BORROWED_PANEL,
    PENDING_BORROW_PANEL,
    PENDING_RETURN_PANEL,
    All_BOOKS_PANEL,
    AVAILABLE_BOOKS_PANEL,
    UNAVAIILABLE_BOOKS_PANEL
}
